apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-1
spec:
  selector:
    matchLabels:
      app: demo-1
  template:
    metadata:
      labels:
        app: demo-1
    spec:
      containers:
        - name: demo-1
          image: same7ammar/demo-1:sha-98a967994bf518f03b80b745eb3f3e2875583509
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-1
spec:
  selector:
    app: demo-1
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
